# Generated by Django 4.0 on 2021-12-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_genre_remove_game_plataform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to='myphotos/%d/%m%Y'),
        ),
    ]
