# Generated by Django 4.0 on 2021-12-31 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegenre',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='games.game'),
        ),
        migrations.AlterField(
            model_name='gameplataform',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plataforms', to='games.game'),
        ),
    ]
