# Generated by Django 4.0 on 2022-01-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_gamegenre_game_alter_gameplataform_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to='games'),
        ),
    ]
